### ISSUE TITLE
I can't get this to run

### ISSUE THREAD

**Issue by DanielDavis05** [jdkennedy45/Discord-Bot#12]
I have installed all the packages from the requirements.txt. I am using Python 3.6.2. Am I doing anything wrong?

Here is the traceback:

> Traceback (most recent call last):
>   File "Main.py", line 343, in <module>
>     client.run(TOKEN)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 519, in run
>     self.loop.run_until_complete(self.start(*args, **kwargs))
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
>     return future.result()
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 491, in start
>     yield from self.connect()
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 448, in connect
>     yield from self.ws.poll_event()
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 431, in poll_event
>     yield from self.received_message(msg)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 390, in received_message
>     func(data)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\state.py", line 509, in parse_guild_create
>     server = self._get_create_server(data)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\state.py", line 483, in _get_create_server
>     server._from_data(data)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\server.py", line 218, in _from_data
>     self._sync(guild)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\server.py", line 250, in _sync
>     channel = Channel(server=self, **c)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\channel.py", line 89, in __init__
>     self._update(**kwargs)
>   File "C:\Users\Daniel\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\channel.py", line 116, in _update
>     self._permission_overwrites.append(Overwrites(**overridden))
> TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by jdkennedy45** [comment]
Hi. Looks like discord just dropped support for discord.py 0.16.12. We are currently rewriting the code to 1.4!
